on:
  push:
    branches: [master]
  pull_request:
  merge_group:

name: Code formatting check

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use the latest stable release
        run: rustup update stable && rustup default stable

      - name: Clippy
        run: cargo fmt --all -- --check
